os:
  - linux
language: cpp
compiler:
  - gcc
env:
  - GCC_VERSION=4.9
install:
  - ./util/buildlibint
  - cd deps
  - git clone https://github.com/wavefunction91/eigen.git
  - git clone https://github.com/wavefunction91/BTAS.git
  - cd ..
script:
  - ./util/travisci_build.sh
